Thunderpad: Theme Class Reference
Theme Class Reference
The Theme class is in charge of reading the specified colors of an inputed XML theme and returning the individual values of each color used to theme the Editor widget.
#include <theme.h>
Public Slots
void readTheme (const QString &theme)
Theme::readTheme.
QColor background ()
Theme::background.
QColor foreground ()
Theme::foreground.
QColor highlightBackground ()
Theme::highlightBackground.
QColor highlightForeground ()
Theme::highlightForeground.
QColor currentLineBackground ()
Theme::currentLineBackground.
QColor lineNumbersBackground ()
Theme::lineNumbersBackground.
QColor lineNumbersForeground ()
Theme::lineNumbersForeground.
QColor others ()
Theme::others.
QColor numbers ()
Theme::numbers.
QColor strings ()
Theme::strings.
QColor keywords ()
Theme::keywords.
QColor comments ()
Theme::comments.
QColor functions ()
Theme::functions.
QColor data_types ()
Theme::data_types.
Public Member Functions
Theme (QObject *parent=0)
Theme::Theme.
Detailed Description
The Theme class is in charge of reading the specified colors of an inputed XML theme and returning the individual values of each color used to theme the Editor widget.
Definition at line 26 of file theme.h.
Constructor & Destructor Documentation
Theme::Theme (QObject * parent = 0) explicit
Theme::Theme.
Parameters
parent Initializes the Theme object, reads the settings and applies the saved theme.
Definition at line 18 of file theme.cpp.
References readTheme().
Member Function Documentation
QColor Theme::background () slot
Theme::background.
Returns
Returns the background color of the text editor
Definition at line 115 of file theme.cpp.
Referenced by Editor::updateSettings().
QColor Theme::comments () slot
Theme::comments.
Returns
Returns the color used to represent comments in the syntax highlighter element.
Definition at line 225 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
QColor Theme::currentLineBackground () slot
Theme::currentLineBackground.
Returns
Returns the background color of the current line
Definition at line 151 of file theme.cpp.
QColor Theme::data_types () slot
Theme::data_types.
Returns
Returns the color used to represent data types in the syntax highlighter element.
Definition at line 245 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
QColor Theme::foreground () slot
Theme::foreground.
Returns
Returns the foreground color of the text editor
Definition at line 124 of file theme.cpp.
Referenced by Editor::updateSettings().
QColor Theme::functions () slot
Theme::functions.
Returns
Returns the color used to represent functions in the syntax highlighter element.
Definition at line 235 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
QColor Theme::highlightBackground () slot
Theme::highlightBackground.
Returns
Returns the background color of the highlighted text
Definition at line 133 of file theme.cpp.
Referenced by Editor::updateSettings().
QColor Theme::highlightForeground () slot
Theme::highlightForeground.
Returns
Returns the foreground color of the highlighted text
Definition at line 142 of file theme.cpp.
Referenced by Editor::updateSettings().
QColor Theme::keywords () slot
Theme::keywords.
Returns
Returns the color used to represent keywords in the syntax highlighter element.
Definition at line 215 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
QColor Theme::lineNumbersBackground () slot
Theme::lineNumbersBackground.
Returns
Returns the background color of the line numbers area
Definition at line 162 of file theme.cpp.
Referenced by Editor::lineNumberAreaPaintEvent().
QColor Theme::lineNumbersForeground () slot
Theme::lineNumbersForeground.
Returns
Returns the foreground color of the line numbers area
Definition at line 173 of file theme.cpp.
Referenced by Editor::lineNumberAreaPaintEvent().
QColor Theme::numbers () slot
Theme::numbers.
Returns
Returns the color used to represent numbers in the syntax highlighter element.
Definition at line 195 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
QColor Theme::others () slot
Theme::others.
Returns
Returns the color used to represent "custom" elements of a programming language
Definition at line 185 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
void Theme::readTheme (const QString & theme) slot
Theme::readTheme.
Parameters
theme the name of the theme that the user wants to load
Reads the requested theme file (themes are stored using the XML format) and applies the color values specified in each theme.xml file
Definition at line 48 of file theme.cpp.
Referenced by Theme(), and Editor::updateSettings().
QColor Theme::strings () slot
Theme::strings.
Returns
Returns the color used to represent text inside quoutations ("") in the syntax highlighter element.
Definition at line 205 of file theme.cpp.
Referenced by SyntaxHighlighter::updateColor().
The documentation for this class was generated from the following files:
theme.h
theme.cpp