Thunderpad: SyntaxHighlighter Class Reference
SyntaxHighlighter Class Reference
The SyntaxHighlighter is in charge of highlighting the contents of the document of the Editor and highlighting relevant matches, such as keywords, types and comments.
#include <syntax-highlighter.h>
Public Slots
void updateColor (Theme *theme)
SyntaxHighlighter::updateColor.
void setLanguage (const QString &lang)
SyntaxHighlighter::setLanguage.
Public Member Functions
SyntaxHighlighter (QTextDocument *parent)
SyntaxHighlighter::SyntaxHighlighter.
Protected Member Functions
void highlightBlock (const QString &text)
SyntaxHighlighter::highlightBlock.
Detailed Description
The SyntaxHighlighter is in charge of highlighting the contents of the document of the Editor and highlighting relevant matches, such as keywords, types and comments.
The SyntaxHighlighter uses the highlighting definitions specified by the XML files found in the resources folder of Thunderpad.
Definition at line 32 of file syntax-highlighter.h.
Constructor & Destructor Documentation
SyntaxHighlighter::SyntaxHighlighter (QTextDocument * parent) explicit
SyntaxHighlighter::SyntaxHighlighter.
Parameters
parent
Definition at line 15 of file syntax-highlighter.cpp.
Member Function Documentation
void SyntaxHighlighter::highlightBlock (const QString & text) protected
SyntaxHighlighter::highlightBlock.
Parameters
text the text to process and highlight
This function is used everytime when the text of the document changes. Instead of rehighlighting all the document when the user tipes something, the function only updates and highlights the new "chunks" of the text document. If you need to highlight all the document, use the rehighlight() function or input all the document's text to the text parameter of this function.
Definition at line 63 of file syntax-highlighter.cpp.
void SyntaxHighlighter::setLanguage (const QString & lang) slot
SyntaxHighlighter::setLanguage.
Parameters
lang the language to apply
Changes the current programming language and rehighlights the document.
The function opens an XML file (based on the lang parementer) that contains information about the selected programming language, such as the language's keywords, functions, variables, constants, etc..
Definition at line 30 of file syntax-highlighter.cpp.
Referenced by Editor::setSyntaxLanguage().
void SyntaxHighlighter::updateColor (Theme * theme) slot
SyntaxHighlighter::updateColor.
Parameters
theme Updates the colors that are used to highlight the document
Definition at line 39 of file syntax-highlighter.cpp.
References Theme::comments(), Theme::data_types(), Theme::functions(), Theme::keywords(), Theme::numbers(), Theme::others(), and Theme::strings().
Referenced by Editor::updateSettings().
The documentation for this class was generated from the following files:
syntax-highlighter.h
syntax-highlighter.cpp