Thunderpad: ToolBar Class Reference
ToolBar Class Reference
The ToolBar class is in charge of creating and configuring a new QToolbarar widget to be used with the Window class.
#include <toolbar.h>
Public Slots
void updateSettings ()
ToolBar::updateSettings.
void setReadOnly (bool ro)
ToolBar::setReadOnly.
void setToolbarText (bool enabled)
ToolBar::setToolbarText.
void setSaveEnabled (bool enabled)
ToolBar::setSaveEnabled.
void update_theme (const QString &theme)
ToolBar::update_theme.
Public Member Functions
ToolBar (QWidget *parent=0)
ToolBar::ToolBar.
void connectSlots (Window *window)
ToolBar::connectSlots.
Detailed Description
The ToolBar class is in charge of creating and configuring a new QToolbarar widget to be used with the Window class.
This class creates the neccessary actions and connects the signals/slots automatically with the connectSlots() function.
Definition at line 28 of file toolbar.h.
Constructor & Destructor Documentation
ToolBar::ToolBar (QWidget * parent = 0)
ToolBar::ToolBar.
Creates and initializes the toolbar
Definition at line 16 of file toolbar.cpp.
References MAC_OS_X, setToolbarText(), and updateSettings().
Member Function Documentation
void ToolBar::connectSlots (Window * window)
ToolBar::connectSlots.
Parameters
window Connects signals/slots between the toolbar and the window
Definition at line 131 of file toolbar.cpp.
References Window::editor(), setReadOnly(), and updateSettings().
Referenced by Window::Window().
void ToolBar::setReadOnly (bool ro) slot
ToolBar::setReadOnly.
Parameters
ro stands for "read only"
Shows/hides the read only button
Definition at line 76 of file toolbar.cpp.
Referenced by connectSlots(), and Window::setReadOnly().
void ToolBar::setSaveEnabled (bool enabled) slot
ToolBar::setSaveEnabled.
Parameters
enabled Enables/disables the save button
Definition at line 89 of file toolbar.cpp.
void ToolBar::setToolbarText (bool enabled) slot
ToolBar::setToolbarText.
Parameters
enabled defines whenever to show the text or not
Shows and hides the text underneath the toolbar icons and resizes the toolbar to an appropiate height.
Definition at line 99 of file toolbar.cpp.
References MAC_OS_X.
Referenced by ToolBar(), and updateSettings().
void ToolBar::update_theme (const QString & theme) slot
ToolBar::update_theme.
Parameters
theme used to determine the location of the icons
Updates the icon theme of the toolbar
Definition at line 183 of file toolbar.cpp.
Referenced by updateSettings().
void ToolBar::updateSettings () slot
ToolBar::updateSettings.
Reads and applies the new settings
Definition at line 159 of file toolbar.cpp.
References MAC_OS_X, setToolbarText(), and update_theme().
Referenced by connectSlots(), and ToolBar().
The documentation for this class was generated from the following files:
toolbar.h
toolbar.cpp