Thunderpad: Window Class Reference
Window Class Reference
The Window class is used to display and configure each element of Thunderpad, such as the Editor widget.
#include <window.h>
Public Slots
void newFile ()
Window::newFile.
void open ()
Window::open.
void setReadOnly (bool ro)
Window::setReadOnly.
void setWordWrap (bool ww)
Window::setWordWrap.
void setToolbarText (bool tt)
Window::setToolbarText.
void setToolbarEnabled (bool tb)
Window::setToolbarEnabled.
void setStatusBarEnabled (bool sb)
Window::setStatusBarEnabled.
void setHCLineEnabled (bool hc)
Window::setHCLineEnabled.
void setLineNumbersEnabled (bool ln)
Window::setLineNumbersEnabled.
void setIconTheme (const QString &theme)
Window::setIconTheme.
void setColorscheme (const QString &colorscheme)
Window::setColorscheme.
void aboutThunderpad ()
Window::aboutThunderpad.
void license ()
Window::license.
void viewHelp ()
Window::viewHelp.
void reportBug ()
Window::reportBug.
void sendFeedback ()
Window::sendFeedback.
void makeContribution ()
Window::makeContribution.
void checkForUpdates ()
Window::checkForUpdates.
void officialWebsite ()
Window::officialWebsite.
Signals
void updateSettings ()
void settingsChanged ()
void readOnlyChanged (bool ro)
Public Member Functions
Window ()
Window::Window.
Editor * editor () const
Window::editor.
ToolBar * toolbar () const
Window::toolbar.
void configureWindow (Window *window)
Window::configureWindow.
void openFile (const QString &file_name)
Window::openFile.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Window::closeEvent.
Detailed Description
The Window class is used to display and configure each element of Thunderpad, such as the Editor widget.
The Window is in charge of connecting and configuring everything together, such as the actions of the menubar with the functions of the text editor. Finally, the Window allows the Application class to create a new window and open a file using the configureWindow() function.
Definition at line 38 of file window.h.
Constructor & Destructor Documentation
Window::Window ()
Window::Window.
Initializes and configures the window
Definition at line 18 of file window.cpp.
References ToolBar::connectSlots(), MenuBar::connectSlots(), settingsChanged(), and updateSettings().
Referenced by newFile(), and openFile().
Member Function Documentation
void Window::aboutThunderpad () slot
Window::aboutThunderpad.
Shows the about dialog.
Definition at line 299 of file window.cpp.
void Window::checkForUpdates () slot
Window::checkForUpdates.
Calls the Updater::checkForUpdates() function and shows a message box if the user is using the latest version of the application. If there's a newer version, the Window::manageUpdates() function will show a message box informing the user about the new release.
Definition at line 361 of file window.cpp.
References Updater::checkForUpdates().
void Window::closeEvent (QCloseEvent * event) protected
Window::closeEvent.
Parameters
event Allows us to ask the user to save changes before closing the document
Definition at line 91 of file window.cpp.
References Editor::maybeSave().
void Window::configureWindow (Window * window)
Window::configureWindow.
Parameters
window the new window to configure
Creates and configures a new Window object.
Definition at line 493 of file window.cpp.
References settingsChanged(), and updateSettings().
Referenced by newFile(), and openFile().
Editor * Window::editor () const
Window::editor.
Returns
Allows other classes to access the text editor.
Definition at line 72 of file window.cpp.
Referenced by ToolBar::connectSlots(), MenuBar::connectSlots(), and openFile().
void Window::license () slot
Window::license.
Opens an external link to display the GNU 3.0 license
Definition at line 307 of file window.cpp.
void Window::makeContribution () slot
Window::makeContribution.
Opens a web browser with a link to contribute
Definition at line 348 of file window.cpp.
void Window::newFile () slot
Window::newFile.
Creates a new window with a blank document.
Definition at line 132 of file window.cpp.
References configureWindow(), and Window().
void Window::officialWebsite () slot
Window::officialWebsite.
Opens a web browser with the official website of Thunderpad
Definition at line 372 of file window.cpp.
void Window::open () slot
Window::open.
Shows a QFileDialog and opens the selected files with the Window::openFile(QString) function.
Definition at line 144 of file window.cpp.
References openFile().
void Window::openFile (const QString & file_name)
Window::openFile.
Parameters
file_name the file to open
Decides whenever to create a new window and load the file or to read the file directly
Definition at line 112 of file window.cpp.
References configureWindow(), editor(), Editor::readFile(), and Window().
Referenced by Application::Application(), Application::event(), and open().
void Window::readOnlyChanged (bool ro) signal
Referenced by setReadOnly().
void Window::reportBug () slot
Window::reportBug.
Opens an external link to create a new issue at GitHub
Definition at line 337 of file window.cpp.
void Window::sendFeedback () slot
Window::sendFeedback.
Allows the user to send feedback by Email
Definition at line 327 of file window.cpp.
void Window::setColorscheme (const QString & colorscheme) slot
Window::setColorscheme.
Parameters
colorscheme Loads the selected color scheme and applies it to the text editor.
Definition at line 270 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::setHCLineEnabled (bool hc) slot
Window::setHCLineEnabled.
Parameters
hc stands for "highlight current" line
Toggles the state of the line highlighting of the text editor.
Definition at line 238 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::setIconTheme (const QString & theme) slot
Window::setIconTheme.
Parameters
theme Changes the icon theme in the toolbar.
Definition at line 285 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::setLineNumbersEnabled (bool ln) slot
Window::setLineNumbersEnabled.
Parameters
ln Toggles the state of the line numbers widget in the text editor
Definition at line 254 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::setReadOnly (bool ro) slot
Window::setReadOnly.
Parameters
ro stands for "read only"
Toggles the read only state of the toolbar and the text editor.
Definition at line 162 of file window.cpp.
References readOnlyChanged(), ToolBar::setReadOnly(), and Editor::setReadOnly().
void Window::setStatusBarEnabled (bool sb) slot
Window::setStatusBarEnabled.
Parameters
sb stands for "statusbar"
Shows/hides the statusbar.
Definition at line 222 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::settingsChanged () signal
Referenced by configureWindow(), setColorscheme(), setHCLineEnabled(), setIconTheme(), setLineNumbersEnabled(), setStatusBarEnabled(), setToolbarEnabled(), setToolbarText(), setWordWrap(), and Window().
void Window::setToolbarEnabled (bool tb) slot
Window::setToolbarEnabled.
Parameters
tb stands for "toolbar"
Shows/hides the toolbar.
Definition at line 207 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::setToolbarText (bool tt) slot
Window::setToolbarText.
Parameters
tt stands for "toolbar text"
Enables/disables the text under the toolbar icons
Definition at line 191 of file window.cpp.
References settingsChanged(), and updateSettings().
void Window::setWordWrap (bool ww) slot
Window::setWordWrap.
Parameters
ww stands for "word wrap"
Enables/disabled word wrapping
Definition at line 175 of file window.cpp.
References settingsChanged(), and updateSettings().
ToolBar * Window::toolbar () const
Window::toolbar.
Returns
Allows other classes to access the toolbar.
Definition at line 81 of file window.cpp.
void Window::updateSettings () signal
Referenced by configureWindow(), setColorscheme(), setHCLineEnabled(), setIconTheme(), setLineNumbersEnabled(), setStatusBarEnabled(), setToolbarEnabled(), setToolbarText(), setWordWrap(), and Window().
void Window::viewHelp () slot
Window::viewHelp.
Opens an external link and displays the documentation.
Definition at line 317 of file window.cpp.
The documentation for this class was generated from the following files:
window.h
window.cpp