Thunderpad: Updater Class Reference
Updater Class Reference
This class is in charge of checking for new updates and (if necessary) notify the user about a new version of WinT Messenger.
#include <updater.h>
Signals
void updateAvailable (bool update_available)
Public Member Functions
Updater (QObject *parent=0)
Updater::Updater.
bool checkForUpdates ()
Updater::checkForUpdates.
Detailed Description
This class is in charge of checking for new updates and (if necessary) notify the user about a new version of WinT Messenger.
Definition at line 31 of file updater.h.
Constructor & Destructor Documentation
Updater::Updater (QObject * parent = 0)
Updater::Updater.
Initializes and configures the updater engine
Definition at line 16 of file updater.cpp.
References checkForUpdates().
Member Function Documentation
bool Updater::checkForUpdates ()
Updater::checkForUpdates.
Returns
Downloads a file from GitHub, calls Updater::fileDownloaded() and returns the value of newUpdate.
Definition at line 39 of file updater.cpp.
Referenced by Window::checkForUpdates(), and Updater().
void Updater::updateAvailable (bool update_available) signal
The documentation for this class was generated from the following files:
updater.h
updater.cpp