Thunderpad: MenuBar Class Reference
MenuBar Class Reference
The MenuBar class is in charge of creating and configuring a new QMenuBar widget to be used with the Window class.
#include <menubar.h>
Public Slots
void updateSettings ()
MenuBar::updateSettings.
Signals
void change_icons (const QString &theme)
void change_color (const QString &theme)
void change_syntax (const QString &lang)
Public Member Functions
MenuBar (QWidget *parent=0)
MenuBar::MenuBar.
void setSaveEnabled (bool enabled)
MenuBar::setSaveEnabled.
void connectSlots (Window *window)
MenuBar::connectSlots.
Detailed Description
The MenuBar class is in charge of creating and configuring a new QMenuBar widget to be used with the Window class.
This class creates the neccessary actions and connects the signals/slots automatically with the connectSlots() function.
Definition at line 32 of file menubar.h.
Constructor & Destructor Documentation
MenuBar::MenuBar (QWidget * parent = 0)
MenuBar::MenuBar.
Creates and configures the menu bar
Definition at line 16 of file menubar.cpp.
References updateSettings().
Member Function Documentation
void MenuBar::change_color (const QString & theme) signal
Referenced by connectSlots().
void MenuBar::change_icons (const QString & theme) signal
Referenced by connectSlots().
void MenuBar::change_syntax (const QString & lang) signal
Referenced by connectSlots().
void MenuBar::connectSlots (Window * window)
MenuBar::connectSlots.
Parameters
window Connect slots between menu bar and window
Definition at line 39 of file menubar.cpp.
References change_color(), change_icons(), change_syntax(), and Window::editor().
Referenced by Window::Window().
void MenuBar::setSaveEnabled (bool enabled)
MenuBar::setSaveEnabled.
Parameters
enabled
Definition at line 30 of file menubar.cpp.
void MenuBar::updateSettings () slot
MenuBar::updateSettings.
Updates the value of the menubar items that are used to change the settings of the application.
Definition at line 116 of file menubar.cpp.
References MAC_OS_X.
Referenced by MenuBar().
The documentation for this class was generated from the following files:
menubar.h
menubar.cpp