Thunderpad: Application Class Reference
Application Class Reference
The Application class is in charge of loading and configuring a new Window when Thunderpad is launched or when the system requests Thunderpad to open a file (for example, when the user selects "Thunderpad" from the Open with...
#include <app.h>
Public Member Functions
Application (int &argc, char **argv)
Application::Application.
int showInitError ()
Application::showInitError.
Protected Member Functions
bool event (QEvent *_event)
Detailed Description
The Application class is in charge of loading and configuring a new Window when Thunderpad is launched or when the system requests Thunderpad to open a file (for example, when the user selects "Thunderpad" from the Open with...
menu in the file manager).
Definition at line 26 of file app.h.
Constructor & Destructor Documentation
Application::Application (int & argc, char ** argv)
Application::Application.
Parameters
argc the number of arguments
argv the data of the arguments
Loads and configures a new QApplication. Then, it processes the system's arguments to load a file or create a new file.
Definition at line 24 of file app.cpp.
References MAC_OS_X, and Window::openFile().
Member Function Documentation
bool Application::event (QEvent * _event) protected
Definition at line 77 of file app.cpp.
References Window::openFile().
int Application::showInitError ()
Application::showInitError.
Returns
Tells the user that the application cannot be executed because there's already a running instance of Thunderpad and exits the application.
Definition at line 63 of file app.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
app.h
app.cpp