Thunderpad: Editor Class Reference
Editor Class Reference
The Editor class implements a simple code editor widget that can be customized using XML files.
#include <editor.h>
Public Slots
void updateSettings ()
Editor::updateSettings.
bool save ()
Editor::save.
bool saveAs ()
Editor::saveAs.
void print ()
Editor::print.
void exportPdf ()
Editor::exportPdf.
void exportHtml ()
Editor::exportHtml.
void selectFonts ()
Editor::selectFonts.
void setReadOnly (bool ro)
Editor::setReadOnly.
void setWordWrap (bool ww)
Editor::setWordWrap.
int find (const QString &query)
Editor::find.
void replace (const QString &query)
Editor::replace.
void replaceAll (const QString &query)
Editor::replaceAll.
void readFile (const QString &file)
Editor::readFile.
bool writeFile (const QString &file)
Editor::writeFile.
void setSyntaxLanguage (const QString &language)
Editor::setSyntaxLanguage.
Signals
void updateTitle ()
This signal is emitted when the title of the document changes.
void settingsChanged ()
Public Member Functions
Editor (QWidget *parent=0)
Editor::Editor.
bool maybeSave ()
Editor::maybeSave.
void lineNumberAreaPaintEvent (QPaintEvent *event)
Editor::lineNumberAreaPaintEvent.
int lineNumberAreaWidth ()
Editor::lineNumberAreaWidth.
Protected Member Functions
void resizeEvent (QResizeEvent *event)
Editor::resizeEvent.
Detailed Description
The Editor class implements a simple code editor widget that can be customized using XML files.
For example, the text editor can load a syntax highlighting definition using a predefined XML file and can also be themed using XML files.
The Editor handles most of the common functions of a text editing application, such as opening, reading, writting, exporting and printing files.
Definition at line 41 of file editor.h.
Constructor & Destructor Documentation
Editor::Editor (QWidget * parent = 0) explicit
Editor::Editor.
Parameters
parent Initializes and configures the editor
Definition at line 17 of file editor.cpp.
Member Function Documentation
void Editor::exportHtml () slot
Editor::exportHtml.
Exports the current file as a HTML file.
Definition at line 309 of file editor.cpp.
void Editor::exportPdf () slot
Editor::exportPdf.
Exports the current file as a PDF file.
Definition at line 301 of file editor.cpp.
int Editor::find (const QString & query) slot
Editor::find.
Parameters
query
Returns
Searches, highlights results for a string and returns the number of matches for the query.
Definition at line 382 of file editor.cpp.
void Editor::lineNumberAreaPaintEvent (QPaintEvent * event)
Editor::lineNumberAreaPaintEvent.
Parameters
event Paints and configures a widget that shows the current line number
Definition at line 40 of file editor.cpp.
References Theme::lineNumbersBackground(), and Theme::lineNumbersForeground().
Referenced by LineNumberArea::paintEvent().
int Editor::lineNumberAreaWidth ()
Editor::lineNumberAreaWidth.
Returns
Calculates the width to be used for the line number area
Definition at line 72 of file editor.cpp.
Referenced by resizeEvent(), and LineNumberArea::sizeHint().
bool Editor::maybeSave ()
Editor::maybeSave.
Returns
Decides if we should save the current file automatically or to ask the user to save the current file.
Definition at line 249 of file editor.cpp.
References save().
Referenced by Window::closeEvent().
void Editor::print () slot
Editor::print.
Shows a dialog that will guide the user to print the current document
Definition at line 293 of file editor.cpp.
void Editor::readFile (const QString & file) slot
Editor::readFile.
Parameters
file the file to open
Opens and loads a file into the text editor
Definition at line 414 of file editor.cpp.
References updateTitle().
Referenced by Window::openFile().
void Editor::replace (const QString & query) slot
Editor::replace.
Parameters
query Uses the Editor::find() function to search for a query and replaces the first match of the query.
Definition at line 395 of file editor.cpp.
void Editor::replaceAll (const QString & query) slot
Editor::replaceAll.
Parameters
query Uses the Editor::find() and Editor::replace() function to replace all matches for the query
Definition at line 405 of file editor.cpp.
void Editor::resizeEvent (QResizeEvent * e) protected
Editor::resizeEvent.
Parameters
e represents the resize event
Updates the location of the line number area
Definition at line 122 of file editor.cpp.
References lineNumberAreaWidth().
bool Editor::save () slot
Editor::save.
Returns
Decides whenever to save the file directly or to open a "Save As" dialog
Definition at line 225 of file editor.cpp.
References saveAs(), and writeFile().
Referenced by maybeSave().
bool Editor::saveAs () slot
Editor::saveAs.
Returns
Opens a "Save As" dialog and writes the current file.
Definition at line 236 of file editor.cpp.
References writeFile().
Referenced by save().
void Editor::selectFonts () slot
Editor::selectFonts.
Shows a QFontDialog and allows the user to change the font used in the text editor.
Definition at line 318 of file editor.cpp.
References settingsChanged().
void Editor::setReadOnly (bool ro) slot
Editor::setReadOnly.
Parameters
ro Toggles the read only feature of the text editor.
Definition at line 352 of file editor.cpp.
Referenced by Window::setReadOnly().
void Editor::setSyntaxLanguage (const QString & language) slot
Editor::setSyntaxLanguage.
Parameters
language Calls the Hightlighter::setLanguage() function and and inputs it the language paramter.
Definition at line 485 of file editor.cpp.
References SyntaxHighlighter::setLanguage().
void Editor::settingsChanged () signal
This signal is emitted when the user changes a feature of the text editor, such as the default font used for editing.
Referenced by selectFonts().
void Editor::setWordWrap (bool ww) slot
Editor::setWordWrap.
Parameters
ww Toggles the state of the word wrapping feature
Definition at line 364 of file editor.cpp.
Referenced by updateSettings().
void Editor::updateSettings () slot
Editor::updateSettings.
Reads and applies the new settings in the text editor
Definition at line 156 of file editor.cpp.
References Theme::background(), Theme::foreground(), Theme::highlightBackground(), Theme::highlightForeground(), MAC_OS_X, Theme::readTheme(), setWordWrap(), and SyntaxHighlighter::updateColor().
void Editor::updateTitle () signal
This signal is emitted when the title of the document changes.
Referenced by readFile(), and writeFile().
bool Editor::writeFile (const QString & file) slot
Editor::writeFile.
Parameters
file the file to write
Returns
Saves the contents of the text editor in
Parameters
file. Returns true if the saving is successful.
Definition at line 446 of file editor.cpp.
References updateTitle().
Referenced by save(), and saveAs().
The documentation for this class was generated from the following files:
editor.h
editor.cpp